// import {Inter} from 'next/font/google'
// import './globals.css'
// import {useLocale} from "next-intl";
// import {notFound} from "next/navigation";
//
// const inter = Inter({subsets: ['latin']})
//
// export const metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }
//
// export default function RootLayout({children, params}) {
//     const locale = useLocale();
//
//     // Show a 404 error if the user requests an unknown locale
//     if (params.locale !== locale) {
//         notFound();
//     }
//
//     return (
//         // <html lang="en">
//         <html lang={locale}>
//         <body className={inter.className}>{children}</body>
//         </html>
//     )
// }


import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';

export default async function LocaleLayout({
                                               children,
                                               params: {locale}
                                           }) {
    // Providing all messages to the client
    // side is the easiest way to get started
    const messages = await getMessages();

    return (
        <html lang={locale}>
        <body>
        <NextIntlClientProvider messages={messages}>
            {children}
        </NextIntlClientProvider>
        </body>
        </html>
    );
}