name: Build and Push Frontend Docker image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Frontend Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Клонирование репозитория
      - name: Check out the repo
        uses: actions/checkout@v4

      # Шаг 2: Авторизация в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Шаг 3: Получение короткого SHA коммита
      - name: Get the short SHA of the commit
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Шаг 4: Сборка Docker-образа
      - name: Build Docker image
        run: docker build -t klimpavlov/hiclass-frontend-react:latest -t klimpavlov/hiclass-frontend-react:${{ env.SHORT_SHA }} .

      # Шаг 5: Отправка Docker-образа в Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push klimpavlov/hiclass-frontend-react:latest
          docker push klimpavlov/hiclass-frontend-react:${{ env.SHORT_SHA }}
